import { loadEnvConfig } from '@next/env';
import { buildAndroidAabFingerprintReport } from './print-android-aab-fingerprint';

type EnvMap = Record<string, string | undefined>;

type AndroidAabFingerprintReport = {
  ok: boolean;
  errors: string[];
  bundlePath?: string;
  signerFingerprint?: string;
  envLine?: string;
};

type StoreReleaseEnvDraftOptions = {
  buildAabFingerprintReport?: (env: EnvMap) => AndroidAabFingerprintReport;
};

type StoreReleaseEnvDraft = {
  content: string;
  warnings: string[];
};

const PUBLIC_HOST_PLACEHOLDER = 'https://<your-production-host>';
const SUPPORT_EMAIL_PLACEHOLDER = 'support@<your-domain>';

function envValue(env: EnvMap, key: string) {
  return (env[key] || '').trim();
}

function hasPlaceholder(value: string) {
  const normalized = value.toLowerCase();
  return (
    !value ||
    value.includes('<') ||
    value.includes('>') ||
    value.includes('你的域名') ||
    value.includes('your-domain') ||
    value.includes('待填写') ||
    normalized.includes('example.com') ||
    normalized.includes('localhost')
  );
}

function releaseValue(env: EnvMap, key: string, fallback: string) {
  const value = envValue(env, key);
  return hasPlaceholder(value) ? fallback : value;
}

function appIdValue(env: EnvMap) {
  const value = envValue(env, 'CAPACITOR_APP_ID');
  return value && !value.toLowerCase().includes('com.example.') ? value : 'com.elevatelife.app';
}

function urlFor(baseUrl: string, path: string) {
  return `${baseUrl.replace(/\/+$/, '')}${path}`;
}

function linesForDraft(env: EnvMap, fingerprint: string | undefined) {
  const publicBaseUrl = releaseValue(env, 'APP_PUBLIC_BASE_URL', PUBLIC_HOST_PLACEHOLDER);
  const supportEmail = releaseValue(env, 'APP_SUPPORT_EMAIL', SUPPORT_EMAIL_PLACEHOLDER);
  const capacitorAppId = appIdValue(env);
  const androidPackageName = releaseValue(env, 'ANDROID_PACKAGE_NAME', capacitorAppId);

  return [
    '# Store release environment draft',
    '# Generated by npm run release:env:draft.',
    '# 不要提交填好后的文件；请放在本机 shell、CI secret manager 或私有 .env.production.local。',
    '# Fill the placeholders, then run npm run release:check and npm run release:smoke.',
    '',
    `APP_PUBLIC_BASE_URL=${publicBaseUrl}`,
    `APP_SUPPORT_EMAIL=${supportEmail}`,
    `CAPACITOR_SERVER_URL=${publicBaseUrl}`,
    `CAPACITOR_APP_ID=${capacitorAppId}`,
    `ANDROID_PACKAGE_NAME=${androidPackageName}`,
    `TWA_MANIFEST_URL=${urlFor(publicBaseUrl, '/manifest.webmanifest')}`,
    `STORE_SCREENSHOT_BASE_URL=${publicBaseUrl}`,
    '',
    'TWA_SIGNING_KEY_PATH=/secure/path/elevate-life-upload.jks',
    'TWA_SIGNING_KEY_ALIAS=elevate-life',
    'ANDROID_KEYSTORE_STORE_PASSWORD=',
    'ANDROID_KEYSTORE_KEY_PASSWORD=',
    `ANDROID_SHA256_CERT_FINGERPRINTS=${fingerprint || ''}`,
    '',
    'ANDROID_NATIVE_PROJECT_DIR=android',
    'IOS_NATIVE_PROJECT_DIR=ios',
    'ANDROID_RELEASE_BUNDLE_PATH=android/app/build/outputs/bundle/release/app-release.aab',
    'ANDROID_RELEASE_APK_PATH=android/app/build/outputs/apk/release/app-release.apk',
    'ANDROID_APKSIGNER_PATH=',
    'IOS_ARCHIVE_PATH=ios/build/ElevateLife.xcarchive',
    'IOS_ARCHIVE_APP_NAME=App.app',
    '',
    'STORE_SCREENSHOT_OUTPUT_DIR=store-screenshots',
    'STORE_SCREENSHOT_USERNAME=demo',
    'STORE_SCREENSHOT_PASSWORD=',
    'REVIEW_ACCOUNT_USERNAME=demo',
    'REVIEW_ACCOUNT_PASSWORD=',
    '',
    'MOBILE_ALLOWED_ANDROID_PERMISSIONS=',
    'MOBILE_ALLOWED_IOS_USAGE_KEYS=',
  ];
}

export function buildStoreReleaseEnvDraft(
  env: EnvMap = process.env,
  options: StoreReleaseEnvDraftOptions = {},
): StoreReleaseEnvDraft {
  const fingerprintReport = (options.buildAabFingerprintReport ?? buildAndroidAabFingerprintReport)(env);
  const warnings = [
    'Replace APP_PUBLIC_BASE_URL and APP_SUPPORT_EMAIL with your 真实 HTTPS 域名 and real support mailbox before release:check.',
    'Add the Play App Signing SHA-256 fingerprint to ANDROID_SHA256_CERT_FINGERPRINTS after Google Play creates it.',
  ];

  if (!fingerprintReport.ok) {
    warnings.push(
      `Could not infer an AAB SHA-256 fingerprint yet: ${fingerprintReport.errors.join(' ') || 'unknown error'}`,
    );
  } else if (fingerprintReport.bundlePath) {
    warnings.push(`Inferred Android AAB SHA-256 from ${fingerprintReport.bundlePath}. Re-run after rebuilding the final AAB.`);
  }

  return {
    content: `${linesForDraft(env, fingerprintReport.signerFingerprint).join('\n')}\n`,
    warnings,
  };
}

function runCli() {
  loadEnvConfig(process.cwd());
  const draft = buildStoreReleaseEnvDraft(process.env);
  console.log(draft.content);
  console.log('# Warnings');
  for (const warning of draft.warnings) console.log(`# - ${warning}`);
}

if (
  process.argv[1]?.endsWith('print-store-release-env-draft.ts') ||
  process.argv[1]?.endsWith('print-store-release-env-draft.js')
) {
  runCli();
}
